### ISSUE TITLE
HTTPS can be only activated in external mode

### ISSUE THREAD

**Issue by vsapronov** [syncloud/platform#162]
HTTPS doesn't make sense in internal mode.
It won't work with real certificate.
Platform should switch http->https when external access switched off.
Platform should not allow to switch http->https when external mode is off.

**Comment by cyberb** [comment]
Just realised that it may complicate testing of some features as chrome for example according to their rules [1] do not allow webrtc in non https.

[1] https://www.chromium.org/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

**Comment by vsapronov** [comment]
Ahhh, I see. So what do we do? I can enforce disabling https from UI when external access is switched off.
Other option would be: just leave it as is - external access and https are independant settings.

The one thing I can't get: if external access is off then (I thought) Let's Encrypt will fail anyway.  How webrtc will be possible on internal device?

**Comment by cyberb** [comment]
We always generate on activation proper Certificate Authority certificate and Server Certificate signed by this CA, so CA can always be imported into a browser trusted store and it becomes green. 
It can be imported into Android trusted store as well and Android browser becomes green as well. 

That is what I do right now as BT router blocks ports under 1024 and I cannot use Let's Encrypt (Certbot) because of that. 

I would leave it separate for now.

**Comment by vsapronov** [comment]
OK, I'm disconnecting these two: external access and https
