### ISSUE TITLE
Can't activate with my own domain

### ISSUE THREAD

**Issue by nunoleite** [syncloud/platform#314]
Hi!
I'm trying Virtualbox version and have configured bridge mode on the network. So, i have an ip on my network.
List of configurations:
my syncloud ip: (ifconfig) 192.168.2.105
I have UPNP disabled on my router.
I have my own domain: domain123.com
Then i have set on my server dns: home.domain123.com to my external ip record A 123.123.123.123

Opening Firefox i go to 192.168.2.105
Open the activation page with address http://192.168.2.105:81
then i choose My own domain and enter: home.domain123.com
and user name and password.

After this the browser returns an insecure page:
"Your connection is not secure"
192.168.2.105 uses an invalid security certificate.
i add a permanent exception
and then the site reloads and starts all over again
no way to get out of this.

I even tried to open ports 80, 81, 443 to 192.168.2.105
and tried to put on my own domain the internal ip 192.168.2.105
And nothing..... nothing works....

Is this really working?
How to solve this?

Thanks

**Comment by cyberb** [comment]
This should work.
Can you try opening https://192.168.2.105

**Comment by cyberb** [comment]
I guess the problem is that after you add exception browser asks to resend data and you say no.
In that case you right it will loop forever exception -> resend data -> no -> exception ... until you say yes :)
"Resend data" is actually a result of our attempt to auto-login a new user using login and password from activation form. Probably that is not a very good idea and we should simply show login page of the activated device.
Let me know if that is what happened and we will disable auto-login feature.

**Comment by nunoleite** [comment]
Hi!
I allways do an exception but it allways ask to resend and i allways resend and then all the same page.
I'm using the VirtualBox version.
Thanks

**Comment by cyberb** [comment]
You right, if you do custom domain activation and not try syncloud domain first it does not work.

Workaround 1:
Activate with syncloud domain first and then reactivate with custom domain.

Workaround 2:
Run this command on device using ssh:
````
sed -i '/\[platform\]/a domain_update_token = 0' /opt/data/platform/user_platform.cfg
````
