### ISSUE TITLE
IPv6 clarification

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#331]
1. Network settings need to tell you more about differrnt modes of operation. Explain the differrnce between IPv6 and IPv4.
2. Detect device and roiter IP version
3. Suggest changes to make device accessible using one of the modes.

**Comment by klmhsb42** [comment]
Now, I understand a little bit more about my problems and why it is not that easy to access my syncloud externaly. I've a _FRITZ!Box 6490 cable_ which comes with _Dual-Stack-Lite (DS-Lite)_. So, I can only access via _IPv6_. The only solution seems to be direct access via a _VPN tunnel_. As this was already opend as issue #298, I wanted to add, that this would be nice to have not only because of privacy issues, furthermore to allow access for a lot of people who are using cabel internet as well. It would be nice to have it with _UDP_ instead of _TCP-Port forwarding_. 

Because I'm able to access my device from home network, I would like to ask, how is it possible to access apps, e.g. nextcloud from private network? If I click on the app symbols, its opening the domaine, `nextcloud.subdomaine.syncloud.it`, but therefore I need external access. Can I access it via `private IP + some Port`?

**Comment by cyberb** [comment]
VPN

Not sure how VPN can help if you cannot access your device. I guess you still have to be in IPv6 network to do that. In that case you will be able to access device services also without vpn. Unless you are talking about more complex vpn setup. Feel free to add more comments on VPN issue so we can discuss it there.

Home access

If you can access device by ip then you should be able to access apps by domain name as long as domain name has the same ip. Can you check your dns with this instruction: https://github.com/syncloud/platform/wiki/Unable-to-access-device-from-local-network

Unfortunately IPv6 only clients need to get public IPv4 from their ISPs or wait for IPv6 on all the networks they are accessing their devices from. For example check your mobile network provider IPv6 status if that is the main external network you use.

**Comment by klmhsb42** [comment]
To be honest, my knowledge about this topic is limited. I’m referring to [this thread](https://forum.vodafone.de/t5/Internet-Telefon-TV-%C3%BCber-Kabel/Externer-Zugriff-auf-FRITZ-Box-6490-nicht-m%C3%B6glich/td-p/1665958) (in german), were same was suggested. Same router and ISP. First, I think you are right, you must be in an extern IPv6 network. But I think my problem is, that I can _only_ access my router via IPv6 and have _only_ a private IPv4 network. Both I _can’t_ change. So, even when I’m accessing from an extern IPv6 network, I can’t access syncloud, because it communicates with the router via IPv4. So, I thought an IPv6 VPN would allow an IPv6 communication between syncloud and router.

**Comment by cyberb** [comment]
Ok, this one we should be able to fix, because syncloud should use ipv6 from ipv6 network.

Can you check your dns record:

Ip for ipv6 network:
````
nslookup -query=AAAA [name].syncloud.it
````

Ip for ipv4 network:
````
nslookup -query=AAAA [name].syncloud.it
````

If you get only ipv4 address, that means you cannot access from ipv4 and we should fix that if you acually have ipv6 ip.

**Comment by cyberb** [comment]
We should update public ipv4 using ipv4 interface, but supply additional ipv6 as it is globally unique.

**Comment by klmhsb42** [comment]
I'm using VM image. I think, I can only get ipv6. I've sent you an screenshot per mail...

**Comment by cyberb** [comment]
We have automayic ipv6/dual stack detection and update both A and AAAA domain names.
Closing this for now untill we have new problems in ipv6 land.
