### ISSUE TITLE
Syncloud backup of files in nextcloud 

### ISSUE THREAD

**Issue by tfhmd1** [syncloud/platform#392]
Hi, how can we backup files either to a remote server or removable hard drive? As most synclouds are run with just one hard drive this would give more security should the hard drive fail.

**Comment by cyberb** [comment]
There are few options here:

1. You can try Syncthing app wiith two Syncloud devices. It is a device to device sync app. Both devices have to be on the same network otherwise additional port has to be open.
As I remember it currently allows to sync only itself files, if that is the case we can fix that.

**Comment by cyberb** [comment]
2. We can extend backup feature to include files but as backup is saved on the same file storage it does not really makes sense inless you want to protect against accidental file removals.

**Comment by cyberb** [comment]
3. At some point we will come with x86 device which will allow multi disk configuration which should protect against single disk failure.

**Comment by chegeiser** [comment]
I just tried using Syncthing to sync between my Syncloud machine and another local machine. It works well, but will not let me access Nextcloud files. I think that is because only the 'nextcloud' user has access to read/write files within the Nextcloud data folders. I tried a symlink on the Syncloud machine - but as expected that didn't let Syncthing access the files either. 

I was not able to create a folder outside of the Syncthing folder and sync that between the two machines. It seems Syncthing will only allowing syncing of files within /home/syncthing/snap/syncthing/####### 

The first image is the one that will sync, the second will not.
![syncthing](https://user-images.githubusercontent.com/17602493/60221105-3f08c380-982d-11e9-9e5f-1aa3b4c3001b.png)

![syncthing2](https://user-images.githubusercontent.com/17602493/60221111-43cd7780-982d-11e9-984b-94256fec0b81.png)

**Comment by cyberb** [comment]
I guess one of the options is to run syncthing under root the same way files app can see all the files on the device.

Another option is to add group permissions or even add ACL but this is too much at this point I would say. We can alway add it in the future when everything is working.

**Comment by cyberb** [comment]
I have pushed a version of syncthing which can access any directory:
````
snap refresh syncthing --channel=master
````

**Comment by cyberb** [comment]
@chegeiser did you try master version?

**Comment by cyberb** [comment]
Syncthing was released to the stable channel.
It should be enough for backup of any file from any device to any device.
