### ISSUE TITLE
[mail] delivery problem

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#417]
1. Need to test if device activates with mixed case user name can send/receive emails.
2. Also users created with usera app cannot receive emails with no such user error even from the same server users. While they can login and send email on thr same server. Mail sending to other servers like gmail does not seem to work or google blocks it properly.

**Comment by cyberb** [comment]
Update your mail app

**Comment by cyberb** [comment]
Mixed case device usernames is still a problem 
Workaround foe now is to reactivate device with lowercase username.
We will have to force device activation username to lower case.

**Comment by klmhsb42** [comment]
After "opening the 2 ports on the router" you write in the wiki "Then use them in setting up your mail app." I don't find a possibility to do this in the roundcube web-interface. I guess this must be changed in a config file itself? Would it be possible to set 993 and 587 as default in the config file while installing the mail app, so that the user has just to open the ports on the router after installation and nothing else?

**Comment by cyberb** [comment]
It is already like this.
These ports are not for roundcube, it should be working out of the box.
These ports are for other mail client apps like K9Mail (android app) or any other you wish to use.

**Comment by cyberb** [comment]
Mixed case login problem should be fixed in latest platform which will force device login to be lower case only.
