### ISSUE TITLE
Dualstack IPv4 switch button

### ISSUE THREAD

**Issue by klmhsb42** [syncloud/platform#505]
Remove entry of local IPv4 address, when there is dual stack _lite_ and use always IPv6.

- Might be hard to detect the difference to real dual stack #468 
- Remove also from VPN setting #438 
- Use IPv6 address for device activation
- And could make opening of port 80 to get Let's Encrypt certificate for IPv6 customers unnecessary? Anway, this will be removed by #360

**Comment by thomasschaeferm** [comment]
Maybe automatically isn't easy. I would like to have the extension (user's decision):
IPv4 (private): IPv4 (public): IPv4 (off)

**Comment by thomasschaeferm** [comment]
I don't want disable IPv6. I want the ability to switch off IPv4. In the meantime don't know which is the right isse number.
![Screenshot_20200426-223315](https://user-images.githubusercontent.com/6906894/80319015-698d2980-880e-11ea-8715-aed6e71d1623.png)

**Comment by klmhsb42** [comment]
> I don't want disable IPv6.

I know, so this would be the right issue. I just thought the solution could be combined with the other issue. I thought disabling Ipv6 extern access could be useful to test own apps (like websites) which you don't to publish yet. I would integrate this in the extern access button, which switches then from ipv6 to privat ipv4 and local hostname.

In this issue, we need a extra button in the syncloud UI, which switches ipv4 on and off.

**Comment by klmhsb42** [comment]
> IPv4 (private): IPv4 (public): IPv4 (off)

Or between privat, public and off.

**Comment by klmhsb42** [comment]
Do you have an additional reason/case why you would like to have _private_ ipv4 on/available?

**Comment by klmhsb42** [comment]
As the syncloud UI should be simple as possible (less buttons).

**Comment by cyberb** [comment]
> Remove entry of local IPv4 address

Remove from where?

**Comment by thomasschaeferm** [comment]
My problem is the delay (example of openvpn above) or fail in case the client tries to connect an invalid IPv4 address. In my case both ipv4 addresses are invalid, the public one cannot be chosen, since you make a reachability test and the private address in a pubic environment is also useless and confuses clients.
Also disabling IPv6 might be reasoned.  Some user (e.g. Deutsche Telekom with dualstack with a router called speedport) cannot open the IPv6-firewall at the moment.

**Comment by thomasschaeferm** [comment]
> As the syncloud UI should be simple as possible (less buttons). In best case, you even don't have to say that there are two IP versions. So that a user can setup without even knowing what a IP address is (I know it's sad, but there are also smartphone users who don't care about it).

Then you have to integrate more checks at syncloud infrastructure site. E.g. at the moment there is only an IPv4-Port check. That has to be extended to IPv6. Only if the tests succeeds - A and or AAAA-Records should be published/assigned.

But people have to make port forwardings (ipv4) / firewall configurations(ipv6) anyway...

**Comment by klmhsb42** [comment]
> > Remove entry of local IPv4 address
> 
> Remove from where?

From A record? Sorry, I'm not the expert on this. 

> IPv4 (private): IPv4 (public): IPv4 (off)

Or change A record by button. That's how I understand this...

**Comment by cyberb** [comment]
OK, looks like more users want to control which IP version is enabled for external access mostly because only one of them is allowing incoming connections on device port (default 443) (which should be fixed on either router or ISP but does not allow users to start using the device right away) 

Our DNS server at syncloud.it validates that the connection to device port can be made before creating DNS A/AAAA records.

I think I could add the following options to External Access:
* IPv6 (only if device has IPv6): 
  * Enabled (AAAA record is created if connection to port validated form outside can be made)
  * Disabled (No AAAA record is created)
* IPv4 (only if device has IPv4): 
  * Public (A record for Public IPv4 is created if connection to port validated form outside can be made)
  * Private (A record for Private IPv4 is created)
  * Disabled (No A record is created)
 
It will not disable IPs on the device.
The name of the page `External Access` is a bit confusing as it does not really enables external but rather helps you to validate if it is possible, but maybe that is ok for now.

**Comment by cvassiliou** [comment]
It sounds good.
If possible add a clear indication if UPnP is used.

**Comment by cyberb** [comment]
![image](https://user-images.githubusercontent.com/885528/163694046-15e6bad3-ca4f-42b3-aa7a-024fa837fb81.png)

Not sure how useful UPnP is as it does not always work or available so it will be dropped for now.

**Comment by cyberb** [comment]
![image](https://user-images.githubusercontent.com/885528/163695056-0473066c-676d-4385-89ce-53e758e209be.png)
