### ISSUE TITLE
Odroid-C2: network is not working

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#516]
Works fine in platform 200130176.
After upgrade to platform 200530379 and reboot no network.

If you experience the issue could you paste the output of this command when it works:
```
cat /etc/network/interfaces
```

and again after upgrade

**Comment by Philipp-2020** [comment]
Dear @cyberb !

**Before upgrade:**
_=> Sending logs was possible!_
root@syncloud:~# cat /etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

**After upgrade:**
_=> Sending logs is NOT possible! There is nothing happening._
root@syncloud:~# cat /etc/network/interfaces
auto lo
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet dhcp
iface eth0 inet6 auto
        dhcp 1

Thank you for your support!
BR Philipp

**Comment by cyberb** [comment]
can you put this into your /etc/network/interfaces and reboot to see if it fixes network
```
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
```

**Comment by Philipp-2020** [comment]
I am sorry, I am not that skilled to problably make it the right way:
_This is, what has been in the interfaces-file:_

> auto lo
> iface lo inet loopback
> 
> allow-hotplug eth0
> iface eth0 inet dhcp
> iface eth0 inet6 auto
>         dhcp 1
>         request_prefix 1

_I deleted the above mentioned text and copied your text into the file:_

> auto lo
> iface lo inet loopback
> 
> auto eth0
> iface eth0 inet dhcp

I hope this is, what you meant?
Anyhow, after reboot the system works fine.
Pihole app was able to be updated to the current version "200602271".
Reboot went fine, Pihole, Syncthing and system is running well, checking for updates is working!! :-)

Only 1 bug:
I am not able to send Log-emails?! There is just a very very short "waiting ring" but nothing happening?!?

**Comment by cyberb** [comment]
Strange thing I just tested C2 with our current image and this network config and network seem to work fine:
```
auto lo
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet dhcp
iface eth0 inet6 auto
        dhcp 1
        request_prefix 1
```
@Philipp-2020 
Can you update system from settings, then set the above config to /etc/network/interfaces and reboot?
Also how did you set this config in the first place if network was not working?

**Comment by Philipp-2020** [comment]
I upgraded my Odroid-C2 to:

- System: 200607393

- Installer: 190627

- Apps used: Pi-Hole, Syncthing (latest version, no upgrades available via UI)

**Status: Syncloud working fine.**

_Settings found in the network config:_
@cyberb : These has been the settings you told me. Settings where changed via copying the file with Filezilla to my PC, editing via Notepad, and copying (and overriding) it back to the Odroid-C2. That is the way I do it...

> auto lo
> iface lo inet loopback
> 
> auto eth0
> iface eth0 inet dhcp

_Settings changed to:_

> auto lo
> iface lo inet loopback
> 
> allow-hotplug eth0
> iface eth0 inet dhcp
> iface eth0 inet6 auto
>         dhcp 1
>         request_prefix 1

Reboot of Odroid-C2.

**Status: Checking for updates via UI is not working. Received an error "string indices must be integers".**
Could this be, because I am using Pi-Hole? I have external access enabled and ports are forwarded from my router.

**=> Therefore I changed everything back to my previous settings. => All working again!**

Recognised points:

- Sending logs is possible and working fine.

- I do not know if it was because of changing the network config, but when hitting the "reboot" button, I got an "oops error" message even though the device made a reboot.
I tried again after getting back to my previous settings, there it was fine.
Maybe it is just on me, but I really would appreciate a shourt window saying "do you really want to reboot/power off" when hitting the reboot or power off button, so you see that something is happening? As I said, with the error messge above, it worked but is sometimes confusing. :)

**BTW: Thank you guys for your great job!!**

**Comment by cyberb** [comment]
Could you try latest image for c2:
https://github.com/syncloud/platform/releases/download/20.06/syncloud-odroid-c2-20.06.img.xz

It should contain new network config and no error for checking updates.

**Comment by Philipp-2020** [comment]
I upgraded my Odroid-C2 to:

- System: 200609406
- Installer: 190627
- Apps used: Pi-Hole, Syncthing (latest version, no upgrades available via UI)

**Status: Syncloud working fine.**
No issues with checking for updates or sending logs! :)

**Comment by cyberb** [comment]
Ok, closing this for now.
