### ISSUE TITLE
Helios64 support

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#544]

**Comment by cyberb** [comment]
@g-provost do you have any linux image for this board so we can give it a try?
Users are asking us :)

**Comment by g-provost** [comment]
@cyberb Yes you can use the latest Armbian images for Helios64 (still Work-in-progress but pretty stable already).

**Comment by cyberb** [comment]
Ah, sorry I did not see, this one right?
https://www.armbian.com/helios64/

**Comment by g-provost** [comment]
Yes :-)

**Comment by cyberb** [comment]
Here is the image to test:
https://github.com/syncloud/platform/releases/download/20.10-rc1/syncloud-helios64-20.06.img.xz

@g-provost one more question, do we still need these configs:
https://github.com/syncloud/image/blob/master/files/helios64/etc/udev/rules.d/90-helios4-hwmon.rules
https://github.com/syncloud/image/blob/master/files/helios64/etc/fancontrol

**Comment by g-provost** [comment]
I will try to test when I can, a bit overload lately.

Yes you need those tweaks, whatever rootfs tweaks with do in armbian should be kept :

https://github.com/armbian/build/tree/master/packages/bsp/helios64

https://github.com/armbian/build/blob/e8f961c9c7b9033cb28ad7faec3a217266d50384/config/sources/families/include/rockchip64_common.inc#L264

https://github.com/armbian/build/blob/e8f961c9c7b9033cb28ad7faec3a217266d50384/config/sources/families/include/rockchip64_common.inc#L321

FYI the filename is wrong, you name it helios4-hwmon instead of helios64-hwmon.

**Comment by cyberb** [comment]
closing for now as image is published and fixes are made. reopen if image does not work: https://github.com/syncloud/platform/releases/download/21.01/syncloud-helios64-21.01.img.xz
