### ISSUE TITLE
two devices in same local network, certificate problem?

### ISSUE THREAD

**Issue by SebastGG** [syncloud/platform#556]
Hello,

i have problems with getting certificate for my second device. I activated my second device an did the port mapping manually. At www.syncloud.it both devices are present.

![image](https://user-images.githubusercontent.com/59542884/100437505-272c1380-30a1-11eb-9a44-39933ca33eab.png)
![image](https://user-images.githubusercontent.com/59542884/100437527-2d21f480-30a1-11eb-811b-002e97148921.png)

Does anyone know how to solve this?

**Comment by cyberb** [comment]
This known limitation of Let's Encrypt domain ownership validation process using http protocol.
HTTP mode expects them to be able to connect to your domain strictly by port 80. Because of that you cannot validate more than one device at a time.
As you know you cannot have two devices behind router be on the same port.

As a workaround, can you map port 80 temporary to your second device, wait for certificate renewal and than map it back to the first one.

We are slowly moving towards DNS validation mode, which will fix that problem (https://github.com/syncloud/platform/issues/461)

**Comment by SebastGG** [comment]
allright, i've already thought something like this. Thanks
