### ISSUE TITLE
[nextcloud] fix transaction lock warning

### ISSUE THREAD

**Issue by cyberb** [syncloud/platform#698]
https://docs.nextcloud.com/server/27/admin_manual/configuration_files/files_locking_transactional.html

**Comment by genderneutralnoun** [comment]
Since I made a thread on the syncloud forum about this, I'd just like to say: I can definitely see that having transactional file locking enabled without the memcache configured seems to make nextcloud very slow. Transactional file locking seems to be a pretty important thing to have set up, so maybe the memcache should be pre-configured in the Nextcloud snap for Syncloud? I wouldn't know what that requires, though.
