### ISSUE TITLE
Webserver stopps after upgrading from v185 to v204

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#82]

**Comment by cyberb** [comment]
Just realized that our automated publishing process was releasing broken builds even when we had failed tests.
Fixed the publisher to not publish red builds.

Build itsefl is fixed in v205.

To upgrade from command line (as web ui is broken) do the fallowing:

/opt/app/sam/bin/sam update
/opt/app/sam/bin/sam upgrade platform
