### ISSUE TITLE
ownCloud - Connection refused with platform v225 and ownCloud v71

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#90]
Secure (HTTPS) - Enabled
8GB USB stick activated - tried both NTFS and ext4

**Comment by cyberb** [comment]
What url are you using, try going from syncloud.it to device then click on app icon.
Send us a screenshot (here or to support@syncloud.it) of the browser message as well please.

**Comment by jpma89** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/7020468/11993003/bed3e68c-aa2c-11e5-9249-710ff32041d4.JPG)

**Comment by cyberb** [comment]
I think I know, you need to activate http then activate https again. To activate new nginx configuration.

You will lose access after first step, so you will have to go through syncloud.it site to find device and activate https.

Or you can use local ip access to do the switch.

**Comment by cyberb** [comment]
Several things to check:
1. DNS name actually corresponds to you public IP.
2. You have right mapping on your router
3. Provider does not block external port

We do automate these things and check for provider firewall, but maybe we have missed something.

**Comment by jpma89** [comment]
I've checked several things. It turned out that accessing ownCloud via the new URL from outside of my own network works fine.

I know that the router from my provider blocks all attempts to access the external IP from the internal network. As a workaruond I added the following line to my /etc/hosts file: <BBB internal IP>   <mybbb>.syncloud.it

This workaround is not working anymore with the new URL structure. I will try to evaluate the configuration options for my router (unfortunately only very limited configuration options in the firmware).

**Comment by cyberb** [comment]
Right new URL format needs exact match for the hostname.

OwnCloud app listens only on owncloud.user.syncloud.it and any other domain names will be automatically handled by default device site. This a problem with routers not allowing to access its public IP from internal network. 

Simple solution is to buy a proper router and install it instead of providers one or in front of it. It may require setting provider router into bridge mode. I can help you if you give me provider name and its router name.

Setting another domain name in hosts will not help as you can see.

Need to think about it for some time.

**Comment by cyberb** [comment]
Actually if you add owncloud.[device].syncloud.it to your hosts file and point it local ip, it should work.
But then you should use local port 80.

**Comment by jpma89** [comment]
Adding [Local IP]   owncloud.[device].syncloud.it to the hosts file works fine for me again even with HTTPS while running platform v327.

Some (cable) providers in Germany (e.g. Unitymedia Kabel BW) provide mandatory routers with limited firmware that does not allow bridge mode for some reason.

Let's keep the workaround with /etc/hosts on the local clients in mind if somebody else runs into the same issues.
